# NumPy

##### This link provide link to compare Matlab and Numpy code :

NumPy for Matlab users
https://docs.scipy.org/doc/numpy-1.14.0/user/numpy-for-matlab-users.html


This has links to compare other tools like Matlab vs R, Matlab vs Python
http://mathesaurus.sourceforge.net/

Official Numpy.org link:
https://numpy.org/devdocs/user/quickstart.html

In [9]:
import numpy as np

a = np.array([1,2,3,4,1])
b = np.array([2,2,2,2,1])

print(a/b**2) # ** squares b
print('a>2',a>2,sep='\n',end='\n\n')

print(a[a>2])

print(a[np.logical_or(a>2,a<1)])

print(a[np.logical_and(np.logical_not(a>1),a<2)])

a[np.array([ True, False, False, False,  True])]


#print(b[np.logical_or(b<2,b>2)])

[0.25 0.5  0.75 1.   1.  ]
a>2
[False False  True  True False]

[3 4]
[3 4]
[1 1]


array([1, 1])

##### NumPy concatenate
NumPy’s concatenate function can be used to concatenate two arrays either row-wise or column-wise. Concatenate function can take two or more arrays of the same shape and by default it concatenates row-wise i.e. axis=0. The resulting array after row-wise concatenation is of the shape 6 x 3, i.e. 6 rows and 3 columns.

In [1]:
height = [1,2,3,4]
weight = [10,1,1,2]

print(height +weight )  #normal array with join both
print([height,weight])  #it becomes list of list

import numpy as np
nph = np.array(height)
npw = np.array(weight)

print(nph+npw)
print([nph, npw])

#now using np.concatenate

np.concatenate((nph,npw)).shape
#print(np.concatenate((nph,npw),axis=0))



[1, 2, 3, 4, 10, 1, 1, 2]
[[1, 2, 3, 4], [10, 1, 1, 2]]
[11  3  4  6]
[array([1, 2, 3, 4]), array([10,  1,  1,  2])]


(8,)

# Numpy - Matrix operations

In [17]:
import numpy as np

B = np.arange(0,16,3)

#A = np.eye(3)
#print(A)

print(B)

B = (B/3*B).reshape(3,2)

print(B)

print(type(B))

print(B.shape)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 0  3  6  9 12 15]
[[ 0.  3.]
 [12. 27.]
 [48. 75.]]
<class 'numpy.ndarray'>
(3, 2)


In [18]:
import numpy as np

m = np.matrix('1 2; 3 4')

print(type(m))

<class 'numpy.matrix'>


| MATLAB                            | NumPy                                                                           | Notes                                                                                                                                                                                                                                                                   |
| --------------------------------- | ------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `ndims(a)`                        | `ndim(a)` or `a.ndim`                                                           | get the number of dimensions of an array                                                                                                                                                                                                                                |
| `numel(a)`                        | `size(a)` or `a.size`                                                           | get the number of elements of an array                                                                                                                                                                                                                                  |
| `size(a)`                         | `shape(a)` or `a.shape`                                                         | get the “size” of the matrix                                                                                                                                                                                                                                            |
| `size(a,n)`                       | `a.shape[n-1]`                                                                  | get the number of elements of the n-th dimension of array `a`. (Note that MATLAB® uses 1 based indexing while Python uses 0 based indexing, See note [INDEXING](https://docs.scipy.org/doc/numpy-1.14.0/user/numpy-for-matlab-users.html#numpy-for-matlab-users-notes)) |
| `[ 1 2 3; 4 5 6 ]`                | `array([[1.,2.,3.], [4.,5.,6.]])`                                               | 2x3 matrix literal                                                                                                                                                                                                                                                      |
| `[ a b; c d ]`                    | `vstack([hstack([a,b]), hstack([c,d])])` or `bmat('a b; c d').A`                | construct a matrix from blocks `a`, `b`, `c`, and `d`                                                                                                                                                                                                                   |
| `a(end)`                          | `a[-1]`                                                                         | access last element in the 1xn matrix `a`                                                                                                                                                                                                                               |
| `a(2,5)`                          | `a[1,4]`                                                                        | access element in second row, fifth column                                                                                                                                                                                                                              |
| `a(2,:)`                          | `a[1]` or `a[1,:]`                                                              | entire second row of `a`                                                                                                                                                                                                                                                |
| `a(1:5,:)`                        | `a[0:5]` or `a[:5]` or `a[0:5,:]`                                               | the first five rows of `a`                                                                                                                                                                                                                                              |
| `a(end-4:end,:)`                  | `a[-5:]`                                                                        | the last five rows of `a`                                                                                                                                                                                                                                               |
| `a(1:3,5:9)`                      | `a[0:3][:,4:9]`                                                                 | rows one to three and columns five to nine of `a`. This gives read-only access.                                                                                                                                                                                         |
| `a([2,4,5],[1,3])`                | `a[ix_([1,3,4],[0,2])]`                                                         | rows 2,4 and 5 and columns 1 and 3. This allows the matrix to be modified, and doesn’t require a regular slice.                                                                                                                                                         |
| `a(3:2:21,:)`                     | `a[ 2:21:2,:]`                                                                  | every other row of `a`, starting with the third and going to the twenty-first                                                                                                                                                                                           |
| `a(1:2:end,:)`                    | `a[ ::2,:]`                                                                     | every other row of `a`, starting with the first                                                                                                                                                                                                                         |
| `a(end:-1:1,:)` or `flipud(a)`    | `a[ ::-1,:]`                                                                    | `a` with rows in reverse order                                                                                                                                                                                                                                          |
| `a([1:end 1],:)`                  | `a[r_[:len(a),0]]`                                                              | `a` with copy of the first row appended to the end                                                                                                                                                                                                                      |
| `a.'`                             | `a.transpose()` or `a.T`                                                        | transpose of `a`                                                                                                                                                                                                                                                        |
| `a'`                              | `a.conj().transpose()` or `a.conj().T`                                          | conjugate transpose of `a`                                                                                                                                                                                                                                              |
| `a * b`                           | `a.dot(b)`                                                                      | matrix multiply                                                                                                                                                                                                                                                         |
| `a .* b`                          | `a * b`                                                                         | element-wise multiply                                                                                                                                                                                                                                                   |
| `a./b`                            | `a/b`                                                                           | element-wise divide                                                                                                                                                                                                                                                     |
| `a.^3`                            | `a**3`                                                                          | element-wise exponentiation                                                                                                                                                                                                                                             |
| `(a>0.5)`                         | `(a>0.5)`                                                                       | matrix whose i,jth element is (a\_ij > 0.5). The Matlab result is an array of 0s and 1s. The NumPy result is an array of the boolean values `False` and `True`.                                                                                                         |
| `find(a>0.5)`                     | `nonzero(a>0.5)`                                                                | find the indices where (`a` > 0.5)                                                                                                                                                                                                                                      |
| `a(:,find(v>0.5))`                | `a[:,nonzero(v>0.5)[0]]`                                                        | extract the columms of `a` where vector v > 0.5                                                                                                                                                                                                                         |
| `a(:,find(v>0.5))`                | `a[:,v.T>0.5]`                                                                  | extract the columms of `a` where column vector v > 0.5                                                                                                                                                                                                                  |
| `a(a<0.5)=0`                      | `a[a<0.5]=0`                                                                    | `a` with elements less than 0.5 zeroed out                                                                                                                                                                                                                              |
| `a .* (a>0.5)`                    | `a * (a>0.5)`                                                                   | `a` with elements less than 0.5 zeroed out                                                                                                                                                                                                                              |
| `a(:) = 3`                        | `a[:] = 3`                                                                      | set all values to the same scalar value                                                                                                                                                                                                                                 |
| `y=x`                             | `y = x.copy()`                                                                  | numpy assigns by reference                                                                                                                                                                                                                                              |
| `y=x(2,:)`                        | `y = x[1,:].copy()`                                                             | numpy slices are by reference                                                                                                                                                                                                                                           |
| `y=x(:)`                          | `y = x.flatten()`                                                               | turn array into vector (note that this forces a copy)                                                                                                                                                                                                                   |
| `1:10`                            | `arange(1.,11.)` or `r_[1.:11.]` or `r_[1:10:10j]`                              | create an increasing vector (see note [RANGES](https://docs.scipy.org/doc/numpy-1.14.0/user/numpy-for-matlab-users.html#numpy-for-matlab-users-notes))                                                                                                                  |
| `0:9`                             | `arange(10.)` or `r_[:10.]` or `r_[:9:10j]`                                     | create an increasing vector (see note [RANGES](https://docs.scipy.org/doc/numpy-1.14.0/user/numpy-for-matlab-users.html#numpy-for-matlab-users-notes))                                                                                                                  |
| `[1:10]'`                         | `arange(1.,11.)[:, newaxis]`                                                    | create a column vector                                                                                                                                                                                                                                                  |
| `zeros(3,4)`                      | `zeros((3,4))`                                                                  | 3x4 two-dimensional array full of 64-bit floating point zeros                                                                                                                                                                                                           |
| `zeros(3,4,5)`                    | `zeros((3,4,5))`                                                                | 3x4x5 three-dimensional array full of 64-bit floating point zeros                                                                                                                                                                                                       |
| `ones(3,4)`                       | `ones((3,4))`                                                                   | 3x4 two-dimensional array full of 64-bit floating point ones                                                                                                                                                                                                            |
| `eye(3)`                          | `eye(3)`                                                                        | 3x3 identity matrix                                                                                                                                                                                                                                                     |
| `diag(a)`                         | `diag(a)`                                                                       | vector of diagonal elements of `a`                                                                                                                                                                                                                                      |
| `diag(a,0)`                       | `diag(a,0)`                                                                     | square diagonal matrix whose nonzero values are the elements of `a`                                                                                                                                                                                                     |
| `rand(3,4)`                       | `random.rand(3,4)`                                                              | random 3x4 matrix                                                                                                                                                                                                                                                       |
| `linspace(1,3,4)`                 | `linspace(1,3,4)`                                                               | 4 equally spaced samples between 1 and 3, inclusive                                                                                                                                                                                                                     |
| `[x,y]=meshgrid(0:8,0:5)`         | `mgrid[0:9.,0:6.]` or `meshgrid(r_[0:9.],r_[0:6.]`                              | two 2D arrays: one of x values, the other of y values                                                                                                                                                                                                                   |
|                                   | `ogrid[0:9.,0:6.]` or `ix_(r_[0:9.],r_[0:6.]`                                   | the best way to eval functions on a grid                                                                                                                                                                                                                                |
| `[x,y]=meshgrid([1,2,4],[2,4,5])` | `meshgrid([1,2,4],[2,4,5])`                                                     |                                                                                                                                                                                                                                                                         |
|                                   | `ix_([1,2,4],[2,4,5])`                                                          | the best way to eval functions on a grid                                                                                                                                                                                                                                |
| `repmat(a, m, n)`                 | `tile(a, (m, n))`                                                               | create m by n copies of `a`                                                                                                                                                                                                                                             |
| `[a b]`                           | `concatenate((a,b),1)` or `hstack((a,b))` or `column_stack((a,b))` or `c_[a,b]` | concatenate columns of `a` and `b`                                                                                                                                                                                                                                      |
| `[a; b]`                          | `concatenate((a,b))` or `vstack((a,b))` or `r_[a,b]`                            | concatenate rows of `a` and `b`                                                                                                                                                                                                                                         |
| `max(max(a))`                     | `a.max()`                                                                       | maximum element of `a` (with ndims(a)<=2 for matlab)                                                                                                                                                                                                                    |
| `max(a)`                          | `a.max(0)`                                                                      | maximum element of each column of matrix `a`                                                                                                                                                                                                                            |
| `max(a,[],2)`                     | `a.max(1)`                                                                      | maximum element of each row of matrix `a`                                                                                                                                                                                                                               |
| `max(a,b)`                        | `maximum(a, b)`                                                                 | compares `a` and `b` element-wise, and returns the maximum value from each pair                                                                                                                                                                                         |
| `norm(v)`                         | `sqrt(dot(v,v))` or `np.linalg.norm(v)`                                         | L2 norm of vector `v`                                                                                                                                                                                                                                                   |
| `a & b`                           | `logical_and(a,b)`                                                              | element-by-element AND operator (NumPy ufunc) [See note LOGICOPS](https://docs.scipy.org/doc/numpy-1.14.0/user/numpy-for-matlab-users.html#numpy-for-matlab-users-notes)                                                                                                |
| `a | b`                           | `logical_or(a,b)`                                                               | element-by-element OR operator (NumPy ufunc) [See note LOGICOPS](https://docs.scipy.org/doc/numpy-1.14.0/user/numpy-for-matlab-users.html#numpy-for-matlab-users-notes)                                                                                                 |
| `bitand(a,b)`                     | `a & b`                                                                         | bitwise AND operator (Python native and NumPy ufunc)                                                                                                                                                                                                                    |
| `bitor(a,b)`                      | `a | b`                                                                         | bitwise OR operator (Python native and NumPy ufunc)                                                                                                                                                                                                                     |
| `inv(a)`                          | `linalg.inv(a)`                                                                 | inverse of square matrix `a`                                                                                                                                                                                                                                            |
| `pinv(a)`                         | `linalg.pinv(a)`                                                                | pseudo-inverse of matrix `a`                                                                                                                                                                                                                                            |
| `rank(a)`                         | `linalg.matrix_rank(a)`                                                         | matrix rank of a 2D array / matrix `a`                                                                                                                                                                                                                                  |
| `a\b`                             | `linalg.solve(a,b)` if `a` is square; `linalg.lstsq(a,b)` otherwise             | solution of a x = b for x                                                                                                                                                                                                                                               |
| `b/a`                             | Solve a.T x.T = b.T instead                                                     | solution of x a = b for x                                                                                                                                                                                                                                               |
| `[U,S,V]=svd(a)`                  | `U, S, Vh = linalg.svd(a), V = Vh.T`                                            | singular value decomposition of `a`                                                                                                                                                                                                                                     |
| `chol(a)`                         | `linalg.cholesky(a).T`                                                          | cholesky factorization of a matrix (`chol(a)` in matlab returns an upper triangular matrix, but `linalg.cholesky(a)` returns a lower triangular matrix)                                                                                                                 |
| `[V,D]=eig(a)`                    | `D,V = linalg.eig(a)`                                                           | eigenvalues and eigenvectors of `a`                                                                                                                                                                                                                                     |
| `[V,D]=eig(a,b)`                  | `V,D = np.linalg.eig(a,b)`                                                      | eigenvalues and eigenvectors of `a`, `b`                                                                                                                                                                                                                                |
| `[V,D]=eigs(a,k)`                 |                                                                                 | find the `k` largest eigenvalues and eigenvectors of `a`                                                                                                                                                                                                                |
| `[Q,R,P]=qr(a,0)`                 | `Q,R = scipy.linalg.qr(a)`                                                      | QR decomposition                                                                                                                                                                                                                                                        |
| `[L,U,P]=lu(a)`                   | `L,U = scipy.linalg.lu(a)` or `LU,P=scipy.linalg.lu_factor(a)`                  | LU decomposition (note: P(Matlab) == transpose(P(numpy)) )                                                                                                                                                                                                              |
| `conjgrad`                        | `scipy.sparse.linalg.cg`                                                        | Conjugate gradients solver                                                                                                                                                                                                                                              |
| `fft(a)`                          | `fft(a)`                                                                        | Fourier transform of `a`                                                                                                                                                                                                                                                |
| `ifft(a)`                         | `ifft(a)`                                                                       | inverse Fourier transform of `a`                                                                                                                                                                                                                                        |
| `sort(a)`                         | `sort(a)` or `a.sort()`                                                         | sort the matrix                                                                                                                                                                                                                                                         |
| `[b,I] = sortrows(a,i)`           | `I = argsort(a[:,i]), b=a[I,:]`                                                 | sort the rows of the matrix                                                                                                                                                                                                                                             |
| `regress(y,X)`                    | `linalg.lstsq(X,y)`                                                             | multilinear regression                                                                                                                                                                                                                                                  |
| `decimate(x, q)`                  | `scipy.signal.resample(x, len(x)/q)`                                            | downsample with low-pass filtering                                                                                                                                                                                                                                      |
| `unique(a)`                       | `unique(a)`                                                                     |                                                                                                                                                                                                                                                                         |
| `squeeze(a)`                      | `a.squeeze()`                                                                   |  

In [32]:
import numpy as np

a = np.array([[1,2,3],[1,1,2]])

print(a.sum(axis = 1))

bar = [1,3.33,'ax',[4],{8:'g'},(9)]

print(bar)
print('b'*3)

print('5.52'.islower())

[6 4]
[1, 3.33, 'ax', [4], {8: 'g'}, 9]
bbb
False


In [35]:
import numpy as np

a = np.array([[2,1,2],[3,9,2]])
a +=5
print(a)
b = a+5
print(b)
print(a[1,2]+b[1,1])

[[ 7  6  7]
 [ 8 14  7]]
[[12 11 12]
 [13 19 12]]
26


In [1]:
b = range(6)
print(b)

for i in b:
    print(i*i)

range(0, 6)
0
1
4
9
16
25


### Matrix- and elementwise- multiplication

| MATLAB/Octave | Python                  | Description                                                                |
| ------------- | ----------------------- | -------------------------------------------------------------------------- |
|  |
| a .\* b       | a \* b or multiply(a,b) | Elementwise operations                                                     |
| a \* b        | matrixmultiply(a,b)     | Matrix product (dot product)                                               |
|               | inner(a,b) or           | Inner matrix vector multiplication $a\\cdot b'$                            |
|               | outer(a,b) or           | Outer product                                                              |
| kron(a,b)     | kron(a,b)               | Kronecker product                                                          |
| a / b         |                         | Matrix division, $b{\\cdot}a^{-1}$                                         |
| a \\ b        | linalg.solve(a,b)<br>   | Left matrix division, $b^{-1}{\\cdot}a$ \\newline (solve linear equations) |
|               | vdot(a,b)               | Vector dot product                                                         |
|               | cross(a,b)              | Cross product                                                              |

In [62]:
from numpy import *

a=array([1,2,3])
b=array([3,1,2])

print('a.*b(in Matlab)  = multiply(a,b) (in python)  = a*b (in python) ',a*b) #this is elementwise multiplication

# a*b : it is doing elementwise multiplication

# a@b / a.dot(b) / inner(a,b) : it is doing inner product or dot product. (It is like a*b' in matlab)

# outer(a,b) : it is doing outer product. (it is like a'*b in matlab)

print('a.dot(b)  = ', a.dot(b)) #in python, this is inner product or dot product, like a*b in Matlab, 

print('a*b.T   = inner(a,b) = ', inner(a,b))

print(' a@b = ', a@b)
print('outer(a,b) = ',  outer(a,b), sep='\n')  #this is outer product , 





a.*b(in Matlab)  = multiply(a,b) (in python)  = a*b (in python)  [3 2 6]
a.dot(b)  =  11
a*b.T   = inner(a,b) =  11
 a@b =  11
outer(a,b) = 
[[3 1 2]
 [6 2 4]
 [9 3 6]]


In [69]:
from numpy import *


a1 = array([[1,2,3],[1,2,3]])
a2 = array([[2,2,2],[1,1,1]])

print('a1@a2.T',a1@a2.T,sep='\n')

print('a1.T@a2',a1.T@a2,sep='\n')

print('inner product of a1,a2', inner(a1,a2),sep='\n',)

#print('division = ',a1/a2)

a1@a2.T
[[12  6]
 [12  6]]
a1.T@a2
[[3 3 3]
 [6 6 6]
 [9 9 9]]
inner product of a1,a2
[[12  6]
 [12  6]]
